services:
  - type: web
    name: mlops-wine-quality-api
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: CONFIG_PATH
        value: configs/params.yaml
      - key: MODEL_PATH
        value: models/model.pkl
      - key: DAGSHUB_USERNAME
        sync: false
      - key: DAGSHUB_TOKEN
        sync: false
